version: '3'

services:
  app:
    container_name: cloud-storage
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
    command: npm run start:dev
    depends_on:
      - db
  db:
    container_name: postgres-db
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass1234
      POSTGRES_DB: nest-db
